---
- name: config apache server
  hosts: all
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: start and enable httpd
      systemd:
        name: httpd
        state: started
        enabled: true

    - name: copy index.html.j2
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: allow http and https in firewalld
      firewalld:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      loop:
        - http
        - https
